AnyKernel: TurKernel flashable zip configurations added
Signed-off-by: Onur BÜBER <onurbuber@engineer.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -26,6 +26,27 @@ ui_printfile() {
     ui_print "$line";
   done < $1;
 }
+
+# insert_line <file> <if search string> <before|after> <line match string> <inserted line>
+insert_line() {
+  local offset line;
+  if ! grep -q "$2" $1; then
+    case $3 in
+      before) offset=0;;
+      after) offset=1;;
+    esac;
+    line=$((`grep -n "$4" $1 | head -n1 | cut -d: -f1` + offset));
+    if [ -f $1 -a "$line" ] && [ "$(wc -l $1 | cut -d\  -f1)" -lt "$line" ]; then
+      echo "$5" >> $1;
+    else
+      sed -i "${line}s;^;${5}\n;" $1;
+    fi;
+  fi;
+}
+ui_print "---------------------------------------------"
+ui_print "* AnyKernel3 by osm0sis @ xda-developers";
+ui_print "* TurKernel by @moonaru"
+ui_print "* Initializing "
 show_progress() { echo "progress $1 $2" >> $OUTFD; }
 file_getprop() { $BB grep "^$2=" "$1" | $BB cut -d= -f2-; }
 setup_mountpoint() {
@@ -142,11 +163,6 @@ umount_all() {
 setup_env() {
   $BOOTMODE && return 1;
   $BB mount -o bind /dev/urandom /dev/random;
-  if [ -L /etc ]; then
-    setup_mountpoint /etc;
-    $BB cp -af /etc_link/* /etc;
-    $BB sed -i 's; / ; /system_root ;' /etc/fstab;
-  fi;
   umount_all;
   mount_all;
   OLD_LD_PATH=$LD_LIBRARY_PATH;
@@ -177,8 +193,7 @@ restore_env() {
   test "$OLD_LD_PRE" && export LD_PRELOAD=$OLD_LD_PRE;
   test "$OLD_LD_CFG" && export LD_CONFIG_FILE=$OLD_LD_CFG;
   umount_all;
-  test -L /etc_link && $BB rm -rf /etc/*;
-  (for dir in /apex /system /system_root /etc; do
+  (for dir in /apex /system /system_root; do
     if [ -L "${dir}_link" ]; then
       rmdir $dir;
       $BB mv -f ${dir}_link $dir;
@@ -189,7 +204,7 @@ restore_env() {
 debugging() {
   case $(basename "$ZIPFILE" .zip) in
     *-debugging)
-      ui_print " " "Creating debugging archive in $DIR...";
+      ui_print "Creating debugging archive in $DIR...";
       test -f /tmp/recovery.log && local log=/tmp/recovery.log;
       $BB tar -czf "$DIR/anykernel3-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" $AKHOME $log;
     ;;
@@ -211,7 +226,7 @@ abort() {
 do_devicecheck() {
   test "$(file_getprop anykernel.sh do.devicecheck)" == 1 || return 1;
   local device devicename match product testname vendordevice vendorproduct;
-  ui_print "Checking device...";
+  ui_print "* Checking device...";
   device=$(getprop ro.product.device 2>/dev/null);
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
@@ -219,14 +234,14 @@ do_devicecheck() {
   for testname in $(file_getprop anykernel.sh 'device.name.*'); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
+        ui_print "* $testname";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort "Unsupported device. Aborting...";
   fi;
 }
 int2ver() {
@@ -241,7 +256,7 @@ int2ver() {
 do_versioncheck() {
   test "$(file_getprop anykernel.sh supported.versions)" || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "Checking Android version...";
+  ui_print "* Checking Android version...";
   supported_ver=$(file_getprop anykernel.sh supported.versions | $BB tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
@@ -259,11 +274,10 @@ do_versioncheck() {
       fi;
     done;
   fi;
-  if [ "$supported" ]; then
-    ui_print "$android_ver" " ";
-  else
-    abort " " "Unsupported Android version. Aborting...";
+  if [ ! "$supported" ]; then
+     abort "* Unsupported Android version. Aborting!";
   fi;
+  ui_print "* Detected android version: $android_ver";
 }
 do_levelcheck() {
   test "$(file_getprop anykernel.sh supported.patchlevels)" || return 1;
@@ -283,9 +297,9 @@ do_levelcheck() {
     hi_lvl=9999-99;
   fi;
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $BB sort -g | $BB grep -n "$parsed_lvl" | $BB grep -q '^2:'; then
-    ui_print "$android_lvl" " ";
+    ui_print "- $android_lvl";
   else
-    abort " " "Unsupported Android security patch level. Aborting...";
+    abort "Unsupported Android security patch level. Aborting...";
   fi;
 }
 dump_moduleinfo() {
@@ -308,10 +322,10 @@ EOF
 }
 do_modules() {
   test "$(file_getprop anykernel.sh do.modules)" == 1 || return 1;
-  local block modcon moddir modtarget module slot umask;
+  local modcon moddir modtarget module umask;
   if [ "$(file_getprop anykernel.sh do.systemless)" == 1 ]; then
     cd $AKHOME/modules;
-    ui_print " " "Creating kernel helper Magisk module...";
+    ui_print "Creating kernel helper Magisk module...";
     if [ -d /data/adb/magisk -a -f $AKHOME/split_img/.magisk ]; then
       umask=$(umask);
       umask 022;
@@ -330,14 +344,7 @@ do_modules() {
     fi;
   else
     cd $AKHOME/modules;
-    ui_print " " "Pushing modules...";
-    if [ -d /dev/block/mapper ]; then
-      for block in system vendor; do
-        for slot in "" _a _b; do
-          $BB blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null;
-        done;
-      done;
-    fi;
+    ui_print "* Installing modules";
     if [ ! -d /postinstall/tmp ]; then
       $BB mount -o rw,remount -t auto /system;
       $BB mount -o rw,remount -t auto /vendor 2>/dev/null;
@@ -373,7 +380,6 @@ do_modules() {
 }
 
 show_progress 1.34 4;
-ui_print " ";
 cleanup;
 mkdir -p $AKHOME/bin;
 cd $AKHOME;
@@ -400,33 +406,27 @@ if [ $? != 0 -o -z "$(ls bin)" ]; then
   abort "Busybox setup failed. Aborting...";
 fi;
 
-if [ -f banner ]; then
-  ui_printfile banner;
-  ui_print " " " ";
-fi;
-
-KERNEL_STRING="$(file_getprop anykernel.sh kernel.string)";
-ui_print "$KERNEL_STRING";
-if [ -f version ]; then
-  ui_print " ";
-  ui_printfile version;
-  ui_print " ";
-fi;
-ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
-
 setup_env;
 
 do_devicecheck;
 do_versioncheck;
 do_levelcheck;
 
-ui_print "Installing...";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
 test -f tools/$CORE || $BB ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
 PATH="$AKHOME/bin:$PATH" home=$AKHOME $BB ash anykernel.sh $2;
 if [ $? != 0 ]; then
   abort;
 fi;
+
+# Copy init scripts
+ui_print "* Patching ramdisk...";
+ui_print "* Patched ramdisk!";
+ui_print "* Flashing Ramdisk and Kernel..."
+$BB mount -o rw,remount -t auto /vendor 2>/dev/null;
+insert_line /vendor/etc/init/hw/init.qcom.rc "init.turkernel.rc" after "import /vendor/etc/init/hw/init.qcom.usb.rc" "import /vendor/etc/init/hw/init.turkernel.rc";
+$BB cp -f $AKHOME/init/init.turkernel.rc /vendor/etc/init/hw/init.turkernel.rc;
+$BB chmod 644 /vendor/etc/init/hw/init.turkernel.rc
 
 do_modules;
 
@@ -437,4 +437,7 @@ if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " " " "Done!";
+ui_print "* Flashed successfully!";
+ui_print "* Thank you for using TurKernel!";
+ui_print "* Powered by AnyKernel3 by @osm0sis";
+ui_print "---------------------------------------------"
